{{- if .Values.issuer.dns.enabled }}
{{- if eq .Values.issuer.provider "route53" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "aws-secret-access-key-secret"
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  aws-secret-access-key: {{ .Values.aws.secretAccessKey | b64enc | quote }}
{{- end }}
{{- end }}
